### ISSUE TITLE
StencilJS ct definition

### ISSUE THREAD

**Issue by junelau** [cypress-io/cypress-ct-definition-template#2]
hi @lmiller1990 , I'm trying to write a definition file for stenciljs. However, stencil isn't a framework, and comes with its own bundling. I had to pick webpack or vite, so went with vite and used all vite's defaults. Never used vite before, so was a leap of faith.

However, I am getting a rather cryptic error message  of `Unexpected identifier 'development'`

There is an example stencil project in my fork of your cypress-ct-solid repo: https://github.com/junelau/cypress-ct-stenciljs

would you mind taking a look please?

**Comment by lmiller1990** [comment]
I tried your project, but I got:

![image](https://github.com/cypress-io/cypress-ct-definition-template/assets/19196536/44fa7334-b7b9-45db-9b31-73af7fae286f)

What is the minimal steps to reproduce?

PS: I do not work on Cypress anymore, but I will still try my best to reply and help you out. I might not reply immediately, though.

**Comment by junelau** [comment]
thanks for looking into it. i fear this isn't the best way to test stencil components with cypress, since stencil is its own server and wrapping it under vite would obscure things even further.
